### ISSUE TITLE
2020.2 书添加完然后呢，在哪里看？

### ISSUE THREAD

**Issue by wjc1243** [41369ly/touch-fish#2]
是在工具栏显示么，如何添加到工具栏啊？

**Comment by wjc1243** [comment]
本来要用的热键都改掉了，还是没用

**Comment by 41369ly** [comment]
直接再编辑区域按下热键即可

**Comment by wjc1243** [comment]
> 
> 
> 直接再编辑区域按下热键即可

编辑区shfit + ↑ 是选中光标位置到上一行的代码

**Comment by 41369ly** [comment]
> > 直接再编辑区域按下热键即可
> 
> 编辑区shfit + ↑ 是选中光标位置到上一行的代码

所以需要避开

**Comment by wjc1243** [comment]
> 
> 
> > > 直接再编辑区域按下热键即可
> > 
> > 
> > 编辑区shfit + ↑ 是选中光标位置到上一行的代码
> 
> 所以需要避开

热键禁用完了，还是不行，估计是版本问题，2020.2.2x64

**Comment by 41369ly** [comment]
> > 直接再编辑区域按下热键即可
> 
> 编辑区shfit + ↑ 是选中光标位置到上一行的代码



> > > > 直接再编辑区域按下热键即可
> > > 
> > > 
> > > 编辑区shfit + ↑ 是选中光标位置到上一行的代码
> > 
> > 
> > 所以需要避开
> 
> 热键禁用完了，还是不行，估计是版本问题，2020.2.2x64

你试一下Alt+→ 在settings里面可以修改热键不需要禁用idea本身的热键

**Comment by coding-cc** [comment]
idea 2019.2 安装完成后, 点击新增报错
`
ava.lang.NoClassDefFoundError: com/intellij/util/ui/AsyncProcessIcon$BigCentered
	at cn.tybblog.touchfish.ui.SettingUi.lambda$new$0(SettingUi.java:32)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)

`

**Comment by signner** [comment]
我也没有。改了键也没啥东西出来。小说都加载完了

**Comment by signner** [comment]
> 直接再编辑区域按下热键即可

没用诶老哥。。我的是2020.1.1的

**Comment by 41369ly** [comment]
> > 直接再编辑区域按下热键即可
> 
> 没用诶老哥。。我的是2020.1.1的

和版本没关系，要不你进群我看下，应该是配置问题

**Comment by signner** [comment]
> > > 直接再编辑区域按下热键即可
> > 
> > 
> > 没用诶老哥。。我的是2020.1.1的
> 
> 和版本没关系，要不你进群我看下，应该是配置问题

配置就那么几个啊==不应该啊。可以的。有qq群号嘛？

**Comment by 41369ly** [comment]
> > > > 直接再编辑区域按下热键即可
> > > 
> > > 
> > > 没用诶老哥。。我的是2020.1.1的
> > 
> > 
> > 和版本没关系，要不你进群我看下，应该是配置问题
> 
> 配置就那么几个啊==不应该啊。可以的。有qq群号嘛？

md里面有1031027500
